### ISSUE TITLE
Cannot install with npm 10 - which library to use for fetching metrics using `execute` endpoint

### ISSUE THREAD

**Issue by oliverbock** [signalfx/signalflow-client-js#8]
I have come here from [this page](https://dev.splunk.com/observability/docs/signalflow/#Client-library-support).  The instructions here say to install using `npm install signalflow`, but [that package](https://www.npmjs.com/package/signalflow) requires a version of npm older than 10 (released in August last year).  Does this package contain deprecated old code, or is this the correct library for querying Splunk Observability Cloud in a new project, and I must downgrade npm?

Is there a plan for upgrading to support npm 10?  When is it likely to be available?

**Comment by seemk** [comment]
Not exactly sure why the constraint was in place, but it's now dropped and `0.3.0` is now available.
